project:
  type: website
  output-dir: docs

website:
  title: "Triangle Sports Competition"
  navbar:
    pinned: true
    background: black
    foreground: white
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: index.qmd#about
      - text: Task
        href: task.qmd
      - text: "Hall of fame"
        href: winners.qmd
      - text: "Resources"
        href: resources.qmd
      - text: "FAQ"
        href: faq.qmd

format:
  html:
    theme: default
    toc: false